### ISSUE TITLE
Image resolution issue for preview  image

### ISSUE THREAD

**Issue by ashish-uft** [Contour-Document-Imaging/contours-ai-example#15]
**Build version**
1.7.0 and below

 
**Detailed description**
We are using image resolution 1280x720 in check capturing process. This makes the amount to be illegible in certain cases where the amount is print in a very small font.

**Comment by faraz-ahmad-uft** [comment]
Image resolution for full check image has been increased to 1920x1080

This is done in v1.8.0

Closing the issue.
