### ISSUE TITLE
Change in color configuration for close icon/button

### ISSUE THREAD

**Issue by ashish-uft** [Contour-Document-Imaging/contours-ai-example#19]
It would be good to have an option to change color of close icon/button, because when we set white background it’s almost invisible.

Example screenshots are attached 
Screenshot #1 - Displays the element on a screen with default colors and properties
Screenshot #2 - Displays the element on that screen with background color #FFFFFF
![#2](https://github.com/Contour-Document-Imaging/contours-ai-example/assets/112614939/0d5c06e1-d526-4b5c-ad98-fa47009800dc)
![#1](https://github.com/Contour-Document-Imaging/contours-ai-example/assets/112614939/4a905559-e1a7-469c-9d47-1a7b6fe6de54)

**Comment by faraz-ahmad-uft** [comment]
This issue has been fixed in 1.8.0

Please refer [Android](https://docs.fttoolbox.com/contoursai/android/images) and [iOS](https://docs.fttoolbox.com/contoursai/ios/images) documentation for more details.

Closing the issue.
