### ISSUE TITLE
Screen blinks at SDK start

### ISSUE THREAD

**Issue by ashish-uft** [Contour-Document-Imaging/contours-ai-example#20]
**Build version**
1.7.0 or below

**Detailed information**
A majority of Alpha & Beta testers for iOS app reported this issue where they were encountering some blinks when entering into the SDK first time.

https://github.com/Contour-Document-Imaging/contours-ai-example/assets/112614939/98fa2f5f-fbd7-4eff-a702-cc678e6cfb36

 
This issue occurs in React native iOS SDK

**Comment by faraz-ahmad-uft** [comment]
This bug has been resolved in v1.9.0.

Closing the issue.
