### ISSUE TITLE
Change in behavior of SDK in background or device lock 

### ISSUE THREAD

**Issue by ashish-uft** [Contour-Document-Imaging/contours-ai-example#21]
Based on comparing the SDK on both iOS and android platforms -

It would be good to have the same behavior (probably closing SDK would be better). 
when we background the app or lock the phone, SDK on iOS is closed, but on Android remains.

**Comment by faraz-ahmad-uft** [comment]
We have closed the SDK when app is moved in the background. This behaviour is consistent with the iOS platform.

Closing the issue.
