### ISSUE TITLE
Change the checkbox color 

### ISSUE THREAD

**Issue by ashish-uft** [Contour-Document-Imaging/contours-ai-example#25]
On iOS we don’t see an option to change checkbox colors (only font color could be changed) and it doesn’t look very good with white background when checked.

**Comment by faraz-ahmad-uft** [comment]
This issue has been fixed in 1.8.0

Please refer [Android](https://docs.fttoolbox.com/contoursai/android/images) and [iOS](https://docs.fttoolbox.com/contoursai/ios/images) documentation for more details.

Closing the issue.
