### ISSUE TITLE
Importing {Logbox} from 'react-native' disabling all logboxes in the app

### ISSUE THREAD

**Issue by ashish-uft** [Contour-Document-Imaging/contours-ai-example#26]
**Build version**
1.7.1 or below

**Detailed information**

In file node_modules/contour-ai-sdk/src/index.tsx there’s such code:
import { LogBox } from 'react-native';
LogBox.ignoreAllLogs();
Importing anything from that file (and we need to import at least startContourSDK) results in disabling all logboxes in the app.

**Comment by faraz-ahmad-uft** [comment]
We have removed this method from our dependency. This change is done in v1.9.0.

Closing the issue.
