### ISSUE TITLE
Image cropped after capturing

### ISSUE THREAD

**Issue by ashish-uft** [Contour-Document-Imaging/contours-ai-example#28]
**Build version**
1.6.0 or below

**Detailed information**

This issue occurred on iOS platform where check images were getting cropped a bit after capturing.

https://github.com/Contour-Document-Imaging/contours-ai-example/assets/112614939/b9e082a9-14f0-4e57-b5aa-107446d6f55c

**Comment by faraz-ahmad-uft** [comment]
This issue has been fixed for iOS in 1.7.0

Closing the issue.
