### ISSUE TITLE
SDK Crash on loader view when there is no enough space in device 

### ISSUE THREAD

**Issue by MennyAlterescu** [Contour-Document-Imaging/contours-ai-example#30]
it seems that user crash on loader screen when they device is low memory ( physical storage) 
most of the devices that crash was between 25- 60 MB but also crash on 278MB
attached crash log 
as you can see it look that the operation that crash is write file to device 
can you tell me how much memory the sdk need 
you can also fix this crash by check if the memory is more than some size and throw error 
![image](https://github.com/Contour-Document-Imaging/contours-ai-example/assets/112861396/26c6438c-2b7e-461f-af5c-c6526a182cd7)

**Comment by faraz-ahmad-uft** [comment]
@MennyAlterescu - We have handled the insufficient storage scenario. SDK requires min 500MB storage to run smoothly.

This issue has been fixed in v1.9.0

Closing the issue.
