### ISSUE TITLE
SDK crashes right after tapping `Begin` on intro screen

### ISSUE THREAD

**Issue by jpeckner** [Contour-Document-Imaging/contours-ai-example#32]
_SDK version_: iOS v1.9.0

_Steps to reproduce:_
1. Call `contoursSDK.initializeSDK()` and present the returned `UIViewController`
2. Tap `Begin`
3. App crashes right afterwards, and sends this to Crashlytics:

<img width="1179" alt="Screenshot 2024-04-24 at 10 59 33 AM" src="https://github.com/Contour-Document-Imaging/contours-ai-example/assets/19365492/0e8b5e96-489b-48b1-92d0-ddee9a798cb0">

_Frequency:_ fortunately, this is very rare so far, so we'd like to fix it quickly before it potentially grows. I also somehow managed to reproduce it in a test build (not sure how it got into that state, only that it did), and the crash kept occurring despite repeatedly relaunching the app and trying again. The only way I found to resolve the crash was to delete and reinstall the app entirely, which isn't an acceptable UX.

Note: to keep app details confidential, I'll privately email the full stack trace, and a video I made of the crash occurring, directly to UrbanFT.

**Comment by faraz-ahmad-uft** [comment]
@jpeckner - This issue has been fixed for iOS in v1.9.1 release.

Closing the issue.
