### ISSUE TITLE
ARM64 Simulator Support

### ISSUE THREAD

**Issue by martintreurnicht** [Contour-Document-Imaging/contours-ai-example#35]
This is the only library we're using at the moment that is forcing us to run our tests against x86 simulator in rosetta which is significantly slower. With apple about to release their 4th generation of ARM desktop chips, this seems like a unnecessary limitation , we need native ARM64 simulator support

**Comment by faraz-ahmad-uft** [comment]
@martintreurnicht - ARM64 simulator support has been added in the SDK. We will release this change in our next version(1.10.0).

**Comment by faraz-ahmad-uft** [comment]
@martintreurnicht - We just released v1.10.0 of our SDK with this fix.

Let us know if you are still facing such issue in the SDK.

**Comment by faraz-ahmad-uft** [comment]
@martintreurnicht - We have reopened this issue as we faced some issue in uploading the app on app store after this update. We have also rolled back the change we did for this issue. We have released a new version 1.10.1.

This issue will be addressed in the future release.

**Comment by martintreurnicht** [comment]
@faraz-ahmad-uft Any idea when this issue will be fixed again?

**Comment by faraz-ahmad-uft** [comment]
@martintreurnicht - We've begun addressing this issue and are aiming to include the update in our upcoming release, which is scheduled for the last week of September. 

I'll keep you informed of any update.

**Comment by faraz-ahmad-uft** [comment]
@martintreurnicht - We have released a new version of Contour AI SDK(1.10.5). 

We have verified it and Its working at our end. Could you please check this at your end as well. Once you confirm we can close this issue.

https://docs.fttoolbox.com/contoursai/changeLog/ios

**Comment by faraz-ahmad-uft** [comment]
We believe this issue has now been resolved.

If you're still encountering the same problem, please create a new GitHub issue.
