### ISSUE TITLE
SDK crashes when user stops/exits check capture flow

### ISSUE THREAD

**Issue by jpeckner** [Contour-Document-Imaging/contours-ai-example#36]
SDK version: iOS v1.9.1
iOS versions: 16.x and 17.x

Steps to reproduce: unclear, given that it takes place inside the Contour SDK flow itself (so we don't have any metrics on it), but based on the stack trace it appears to be happening when the user is exiting the flow:

<img width="1221" alt="Screenshot 2024-07-12 at 1 10 55 PM" src="https://github.com/user-attachments/assets/39f38ead-a1fa-403b-b44f-4f8e445d567d">

Frequency: fortunately, this is very rare so far, but we'd still like to see it fixed.

**Comment by faraz-ahmad-uft** [comment]
@jpeckner - As per shared logs, we have done some changes in the SDK. Although we could not replicate it at our end.

We have released a new version(1.10.0) of Contour AI SDK for native iOS and we believe that this issue has been fixed.

If you are still facing this crash in your app, please reopen this issue.

Closing this for now.
